### ISSUE TITLE
HTML5 - Valid with missing </head> tag

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/Unicorn#139]
**Reported by gergo on 1 Dec 2010 23:18 UTC**
Hi,

I guess I found a bug in the validator.
I just tried HTML5 today for the first time, and accidentally forgot to write the </head> tag.

The bug is, this code below is still reported as valid.

Best regards,
Gergo Koos

**Comment by vivienlacourba** [comment]
**Comment by anonymous on 23 Jun 2011 20:31 UTC**
still exists

**Comment by vivienlacourba** [comment]
**Comment by Larae Iacono on 8 Jan 2014 12:00 UTC**
What is in the content of a copyright waiver ? I need to make one and need to know what it includes?

**Comment by jean-gui** [comment]
Closing tag for head elements is optional
