### ISSUE TITLE
Bug found 8/21/2011

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/Unicorn#158]
**Reported by developer on 21 Aug 2011 18:07 UTC**
Love your site and service!
 However, I get the following messages in error: 

URI: http://archives.appliedapologetics.org/css/styles.css
27		 body	You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.	
40		 table	You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.

I have both color and background-color set for both table and body.  If I remove one, it complains its missing (as it should - i.e., remove color but keep background-color, or v.v.)  If I have both color and background-color, then I get the errors.

FYI

**Comment by vivienlacourba** [comment]
**Comment by developer@dokimay.com on 21 Aug 2011 18:10 UTC**
Replying to [developer@](ticket:208):

The original url for the evaluation is http://archives.appliedapologetics.org/bstdy/51_col/index.php and it refers back to the .css denoted above

> Love your site and service!
>  However, I get the following messages in error: 
> 
> URI: http://archives.appliedapologetics.org/css/styles.css
> 27		 body	You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.	
> 40		 table	You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.
> 
> I have both color and background-color set for both table and body.  If I remove one, it complains its missing (as it should - i.e., remove color but keep background-color, or v.v.)  If I have both color and background-color, then I get the errors.
> 
> FYI

**Comment by jean-gui** [comment]
These were warnings that no longer seem to be present.
