### ISSUE TITLE
You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/Unicorn#163]
**Reported by sakthi on 24 Nov 2011 13:01 UTC**
You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.

 how to solve this problem?

**Comment by vivienlacourba** [comment]
**Comment by anonymous on 8 Dec 2013 02:18 UTC**
Replying to [sakthi@](ticket:220):
> You have no color set (or color is set to transparent) but you have set a background-color. Make sure that cascading of colors keeps the text reasonably legible.
> 
> 
>  how to solve this problem?

**Comment by jean-gui** [comment]
That used to simply be a warning. It is not displayed anymore
