### ISSUE TITLE
Validator consideres in2 on feComposite to be a required attribute

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/Unicorn#178]
**Reported by aaron on 12 Nov 2013 16:29 UTC**
The SVG spec at http://www.w3.org/TR/SVG/filters.html#feCompositeIn2Attribute says that in2 on feComposite operates like in, and every SVG implementation I can get my hands on interprets it to be non-required; however, the validator says that it is.

By implementors it seems to be interpreted unambiguously to be non-required, with the same defaults as `in'.

P.S. The SVG validator is unreachable most of the time, I wasn't able to get it to try again after the first time it worked.

**Comment by jean-gui** [comment]
Whether this is an actual bug or not, I believe it is fixed now that we use Nu HTML Checker.
