### ISSUE TITLE
Parse Error Lexical error at line 1, column 1

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/Unicorn#179]
**Reported by ivan spires on 5 Mar 2014 22:41 UTC**
I have climbed through all the discussions on this matter and no one seems to be able to give an answer for this error. I enter the file directly and the file (cyberfanz.com/styles/cyberfanz_style.min.css.gz) and the W3C CSS Validator says it's CSS level 3 but when I place the icon on my website the error comes up when you try to use the icon with the link to the validator the error comes up. What is with this...the file is good when uploaded but the link back to the validation result is in error? I do not know how to correct this error and everyone else has this error with different "somethings" after ...like mine says "Encountered: "\u001f" (31), after : "" and others have the same error with different "afters". Can the W3C respond to me on this and tell me why everything was working one day and then the next....error after error

**Comment by jean-gui** [comment]
This is a compressed file. I believe most validators only support uncompressed resources.
