### ISSUE TITLE
A critical error has occurred.

### ISSUE THREAD

**Issue by validator-lover** [w3c/Unicorn#203]
Unicorn has problem:
"A critical error has occurred.
class org.apache.xmlbeans.XmlException
error: Reference to undefined entity: nbsp
org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3486)
org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1276)
org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1263)
org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)
org.w3.x2009.x10.unicorn.observationresponse.ObservationresponseDocument$Factory.parse(Unknown Source)
org.w3c.unicorn.response.impl.DefaultResponseXBeans.<init>(DefaultResponseXBeans.java:60)
sun.reflect.GeneratedConstructorAccessor4810.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.w3c.unicorn.response.ResponseFactory.getResponse(ResponseFactory.java:24)
org.w3c.unicorn.request.URIRequest.doRequest(URIRequest.java:141)
org.w3c.unicorn.RequestThread.run(RequestThread.java:66)"

and something is wrong with this page... 
https://validator.w3.org/unicorn/check?ucn_uri=https%3A%2F%2Fgithub.com%2Fw3c%2FUnicorn%2Fissues&ucn_lang=en&ucn_task=conformance#

**Comment by jean-gui** [comment]
I believe that's due to the feed validator having recently been updated. We're looking into the issue.

**Comment by jean-gui** [comment]
Feed validator has been fixed, which indeed solved this issue.
