### ISSUE TITLE
validator is unreachable 

### ISSUE THREAD

**Issue by gerland** [w3c/Unicorn#215]
"Nu Html Checker" is unreachable.
"W3C CSS Validator (Level 2.1)" is unreachable.
"W3C CSS Validator (Level 3)" is unreachable.
"Feed Validator" is unreachable.
There is no result to display.

This has been happening since Friday, February 25, 2002.
Thanks,
Jim...

**Comment by HeRo002** [comment]
Yes! It still doesn't work. It worked a few weeks ago.

**Comment by gerland** [comment]
A critical error has occurred.
class org.apache.xmlbeans.XmlException
error: Unexpected end of file after null
org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3486)
org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1276)
org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1263)
org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)
org.w3.x2009.x10.unicorn.observationresponse.ObservationresponseDocument$Factory.parse(Unknown Source)
org.w3c.unicorn.response.impl.DefaultResponseXBeans.<init>(DefaultResponseXBeans.java:60)
jdk.internal.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
org.w3c.unicorn.response.ResponseFactory.getResponse(ResponseFactory.java:24)
org.w3c.unicorn.request.URIRequest.doRequest(URIRequest.java:141)
org.w3c.unicorn.RequestThread.run(RequestThread.java:66)

**Comment by SWRSweb** [comment]
Still happening.
That's a good 5 or 6 weeks now.
Has the tool been abandoned?

**Comment by jean-gui** [comment]
Unicorn should work again now.
